name: Notify garden after note update

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger garden build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GARDEN_TOKEN }}" \
            https://api.github.com/repos/theopaolo/garden/dispatches \
            -d '{"event_type":"notes-updated"}'
